---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: analytics
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30300