auth:
  database: analytics
  password: postgres # default user: postgres

primary:
  initdb:
    scripts:
      init.sql: |
        create table tick_data (
          window_start timestamp,
          window_end timestamp,
          open float,
          high float,
          low float,
          close float,
          volume float
        );